theme: jekyll-theme-minimal
title: cookiecutter-pyspark-cloud
logo: /doc/img/logo.png
description: Zero to PySpark on AWS EMR - quickly, sensibly.
show_downloads: true
google_analytics: "UA-126726744-2"
markdown: CommonMarkGhPages
